JobSearch.PL/Controllers/CreateController.cs
namespace JobSearch.PL.Controllers
{
    using System;
    using System.Web;
    using BLL.Services;
    using System.Web.Mvc;
    using JobSearch.BLL.Dto;
    using JobSearch.PL.Models;
    using System.Threading.Tasks;
    using Microsoft.AspNet.Identity.Owin;

    public class CreateController : Controller
    {
        private static string _path;
        private static int _vacancyId, _userId;
        private static string PhotoPath { get; set; }
        private readonly JobSearchService service;
        private ApplicationUser CurrentEmployer { get; set; }

        #region SignInManager & UserManager:
        private ApplicationSignInManager _signInManager;
        public ApplicationSignInManager SignInManager
        {
            get => _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            private set => _signInManager = value;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get => _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            private set => _userManager = value;
        }
        #endregion

        public CreateController()
        {
            service = new JobSearchService(_829528a_441d_484m_862i_22475963ffdn.Credential.ConnStr);
        }

        [HttpGet]
        public async Task<ActionResult> Vacancy(string emplEmail)
        {
            var categories = await service.ReadCategoriesAsync();
            ViewBag.Categories = new SelectList(categories, "Id", "Name");
            ViewBag.Employer = CurrentEmployer = await UserManager.FindByEmailAsync(emplEmail);
            _userId = CurrentEmployer.UserId;
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Vacancy(VacancyDto vacancy)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    vacancy.Photo = PhotoPath;
                    vacancy.DatePublish = DateTime.Now;
                    vacancy.EmployerId = _userId;
                    service.Insert(vacancy);
                    return RedirectToAction("Index", "Home");
                }
                catch 
                {
                    var categories = await service.ReadCategoriesAsync();
                    ViewBag.Categories = new SelectList(categories, "Id", "Name");
                    ViewBag.Employer = CurrentEmployer;
                    return View();
                }
            }
            ViewBag.Categories = await service.ReadCategoriesAsync();
            return View();
        }

        #region Upload product photo[Post]:
        [HttpPost]
        public ActionResult PhotoUpload()
        {
            if (Request.Files.Count > 0)
            {
                try
                {
                    HttpFileCollectionBase files = Request.Files;
                    for (int i = 0; i < files.Count; i++)
                    {
                        HttpPostedFileBase file = files[i];

                        if (Request.Browser.Browser.ToUpper() == "IE" || Request.Browser.Browser.ToUpper() == "INTERNETEXPLORER")
                        {
                            string[] testfiles = file.FileName.Split(new char[] { '\\' });
                            PhotoPath = testfiles[testfiles.Length - 1];
                        }
                        else PhotoPath = file.FileName;
                        _path = System.IO.Path.Combine(Server.MapPath($"~/Images/Vacancies/{PhotoPath}"));
                        file.SaveAs(_path);
                    }

                    return Json("Upload!");
                }
                catch (Exception ex)
                {
                    return Json("Error occurred. Error details: " + ex.Message);
                }
            }
            else return Json("U should to upload image!");
        }
        #endregion
    }
}

JobSearch.PL/Controllers/DeleteController.cs
namespace JobSearch.PL.Controllers
{
    using System.Linq;
    using BLL.Services;
    using System.Web.Mvc;

    public class DeleteController : Controller
    {
        private readonly JobSearchService service;

        public DeleteController()
        {
            service = new JobSearchService(_829528a_441d_484m_862i_22475963ffdn.Credential.ConnStr);
        }

        [HttpGet]
        public ActionResult Vacancy(int? id)
        {
            return View(service.ReadAll().FirstOrDefault(v => v.Id == id));
        }

        [HttpPost]
        public ActionResult Vacancy(int id)
        {
            service.Delete(service.ReadAll().FirstOrDefault(v => v.Id == id));
            return RedirectToAction("Index", "Home");
        }
    }
}

JobSearch.PL/Controllers/EditController.cs
namespace JobSearch.PL.Controllers
{
    using System;
    using System.Web;
    using System.Linq;
    using BLL.Services;
    using System.Web.Mvc;
    using JobSearch.BLL.Dto;
    using JobSearch.PL.Models;
    using System.Threading.Tasks;
    using Microsoft.AspNet.Identity.Owin;

    public class EditController : Controller
    {
        private static DateTime DatePublish { get; set; }
        private static string PhotoName { get; set; }
        private readonly JobSearchService service;
        private ApplicationUser CurrentEmployer { get; set; }

        #region SignInManager & UserManager:
        private ApplicationSignInManager _signInManager;
        public ApplicationSignInManager SignInManager
        {
            get => _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            private set => _signInManager = value;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get => _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            private set => _userManager = value;
        }
        #endregion

        public EditController()
        {
            service = new JobSearchService(_829528a_441d_484m_862i_22475963ffdn.Credential.ConnStr);
        }

        [HttpGet]
        public async Task<ActionResult> Vacancy(int? id, string emplEmail)
        {
            var categories = await service.ReadCategoriesAsync();
            ViewBag.Categories = new SelectList(categories, "Id", "Name");
            ViewBag.Employer = CurrentEmployer = await UserManager.FindByEmailAsync(emplEmail);
            var vacancy = service.ReadAll().FirstOrDefault(v => v.Id == id);
            PhotoName = vacancy.Photo;
            DatePublish = vacancy.DatePublish;
            return View(vacancy);
        }

        [HttpPost]
        public ActionResult Vacancy(VacancyDto vacancy)
        {
            if (vacancy.Photo == null)
                vacancy.Photo = PhotoName;
            if(vacancy.DatePublish == DateTime.MinValue)
                vacancy.DatePublish = DatePublish;
            service.Update(vacancy);
            return RedirectToAction("Index", "Home");
        }
    }
}

JobSearch.PL/Controllers/MessageController.cs
namespace JobSearch.PL.Controllers
{
    using BLL.Dto;
    using System.Web;
    using System.Linq;
    using System.Web.Mvc;
    using JobSearch.BLL.Services;
    using System.Threading.Tasks;
    using Microsoft.AspNet.Identity.Owin;

    public class MessageController : Controller
    {
        private readonly JobSearchService service;
        private static Models.ApplicationUser CurrentUser { get; set; }
        private static int _senderId, _recipientId;

        public MessageController()
        {         
            service = new JobSearchService(_829528a_441d_484m_862i_22475963ffdn.Credential.ConnStr);
        }

        #region SignInManager & UserManager:
        private ApplicationSignInManager _signInManager;
        public ApplicationSignInManager SignInManager
        {
            get => _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            private set => _signInManager = value;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get => _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            private set => _userManager = value;
        }
        #endregion

        public async Task<ActionResult> Inbox(string userName)
        {
            var im = UserManager.Users.FirstOrDefault(u => u.Email == userName);
            var messages = await service.ReadMessagesAsync();
            var myMessages = messages.Where(m => m.RecipientId == im.UserId);
            ViewBag.Sender = userName;
            return View(myMessages);
        }

        public async Task<ActionResult> FullMessage(int msgId)
        {
            var messages = await service.ReadMessagesAsync();
            var msg = messages.FirstOrDefault(m => m.Id == msgId);
            msg.IsReviwed = true;
            _senderId = msg.SenderId;
            _recipientId = msg.RecipientId;
            await service.UpdateMessageAsync(msgId);
            ViewBag.Recipient = UserManager.Users.FirstOrDefault(u => u.UserId == msg.SenderId);
            ViewBag.Sender = UserManager.Users.FirstOrDefault(u => u.UserId == msg.RecipientId);
            return View(msg);
        }

        [HttpPost]
        public async Task<ActionResult> Send(EmailData mailInfo)
        {
            await service.InsertAsync(new MessageDto
            {
                Title = mailInfo.Title,
                SenderId = _senderId,
                RecipientId = _recipientId,
                TextMessage = mailInfo.Message,
                DateMessage = System.DateTime.Now,
                IsReviwed = false
            });
            return RedirectToAction("Index", "Home", new { isRespond = "sent"});
        }

        public async Task<ActionResult> Respond(string userEmail, string vacancyTitle, int recipient)
        {
            CurrentUser = UserManager.Users.FirstOrDefault(m => m.Email == userEmail);
            await service.InsertAsync(
                new MessageDto
                {
                    Title = $"Новий відгук на вакансію '{vacancyTitle}'",
                    TextMessage = $"Доброго дня мене звати {CurrentUser.FirstName} {CurrentUser.LastName}|" +
                    $"Мої скіли: {CurrentUser.Skills}|Досвід роботи: {CurrentUser.Experience}|" +
                    $"Місто: {CurrentUser.City}|Мої контакти: {CurrentUser.Email}",
                    SenderId = CurrentUser.UserId,
                    RecipientId = recipient,
                    DateMessage = System.DateTime.Now,
                    IsReviwed = false
                });
            return RedirectToAction("Index", "Home", new { isRespond = "respond"});
        }

        public class EmailData
        {
            public string Title { get; set; }
            public string Message { get; set; } = string.Empty;
        }
    }
}

JobSearch.PL/Views/Home/FullVacancy.cshtml
@model JobSearch.BLL.Dto.VacancyDto
@{
    ViewBag.Title = "Full Article";
    JobSearch.BLL.Dto.VacancyDto vacancy = Model;
    string Path = "~/Images/Vacancies/" + vacancy.Photo;
}

<h6 style="font-family:'Times New Roman';font-weight:bold;text-align:center;padding:30px;color:darkblue">
    <span>Date of action:&nbsp;</span> @DateTime.UtcNow
</h6>

<div class="container">
    <div class="row clearfix" style="width:70%;margin:auto">
        <div class="col">
            <div class="card single_post" style="padding:12px">
                <div class="body" style="overflow:auto">
                    <div class="img-post">
                        <img class="d-block img-fluid" width="100%" height="100%" src="@Url.Content(Path)" alt="Image doesn't upload..'">
                    </div>
                    <h3 style="text-decoration:none;font-weight:bold;color:blue;font-family:'Palatino Linotype'">
                        @vacancy.JobTitle
                    </h3>
                    <h4 style="font-family:'Times New Roman'">
                        @vacancy.JobDescription
                    </h4>
                </div>
                <div class="row">
                    <div class="col" style="text-align:left;color:darkblue;font-weight:bold">
                        <span>Оплата(ЗП):</span><span>&nbsp;@vacancy.JobPayment</span>
                    </div>
                    <div class="col" style="text-align:right;font-weight:bold;color:darkred">
                        <small style="">Дата публікації:</small>&nbsp;
                        <small>@vacancy.DatePublish</small>
                    </div>
                </div>
            </div>
        </div>
        @if (ViewBag.IsLogin == true)
        {
            <div class="row" style="text-align:center">
                <div class="col">
                    <hr />
                    @Html.ActionLink("Remove", "vacancy", "Delete",
                       new { id = vacancy.Id }, new { @class = "btn btn-danger", style = "text-decoration:none" })
                </div>
            </div>
        }
    </div>

    <div class="row" style="text-align:center;margin-top:12px">
        <hr />
        <div class="col">
            @Html.ActionLink("<-- Назад до ваканцій", "Index", "Home", null,
              new { @class = "btn btn-default", style = "background-color:#353535;color:white" })
        </div>
    </div>
</div>

JobSearch.PL/Views/Home/Index.cshtml
@model IEnumerable<JobSearch.BLL.Dto.VacancyDto>
@{
    ViewBag.Title = "Main Page";
    var role = ViewBag.Role;
}

<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />

<div class="row" style="font-family:'Times New Roman';font-weight:bold;text-align:left;margin-top:108px;color:darkblue">
    @if (ViewBag.UserId != 0)
    {
        <hr />
        <div class="col" style="text-align:left">
            <h6 style="font-weight:bold">
                @ViewBag.WelcomeStr
            </h6>
        </div>
        if (role == "RegisterUser")
        {
            <div class="col" style="text-align:right">
                @Html.ActionLink("Моя анкета", "UserProfile", "Home", null, new { id = "profile" })
            </div>
        }
        else
        {
            <div class="col" style="text-align:right">
                @Html.ActionLink("Розмістити нову вакансію", "Vacancy", "Create", new { emplEmail = ViewBag.MyEmail }, new { id = "profile" })
            </div>
        }
        <hr />
    }
</div>

<div class="row" style="text-align:center;width:660px;margin:auto">
    @using (Html.BeginForm("Index", "Home", FormMethod.Get))
    {
        <div class="col input-group" style="margin-top:10px">
            <div class="form-outline" style="">
                <select id="searchBy" name="searchBy" class="form-select">
                    <option value="0" selected="selected">Пошук по:</option>
                    <option value="1">
                        Назва вакансії
                    </option>
                    <option value="2">
                        Назва компанії
                    </option>
                </select>
            </div>
            <div class="form-outline">
                <input type="text" class="form-control search" style="width:360px" id="emailBy" name="emailBy" placeholder="Введіть назву вакансії, або назву компанії" onfocus="this.placeholder = ''" onblur="this.placeholder = 'search'" />
                <label class="form-label" for="search"></label>
            </div>
            <div class="form-outline">
                <button style="" type="submit" class="btn btn-primary">
                    <i class="fas fa-search"></i>Знайти
                </button>
            </div>
        </div>
    }
</div>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script>
    var emailBy = document.getElementById("emailBy");
    var e = document.getElementById("searchBy");
    var value = e.value;
    var searchBy = e.options[e.selectedIndex].text;
    var search = { srchBy: searchBy, mailBy: searchBy };
    $.ajax({
        contentType: 'application/json; charset=utf-8',
        dataType: 'json',
        type: 'GET',
        url: '/Index/Index',
        data: search,
        success: function (result) {
            alert(result);
        }
    });
</script>

@if (ViewBag.IsRespond == true)
{
    <div style="" class="alert alert-success alert-dismissible">
        <a href="~/Home/CloseAlerts" class="close" data-dismiss="alert" style="text-decoration: none;text-align:right; font-size: large; color: #82822f"
           aria-label="close">&times;</a>
        <h4 style="text-align:center;color:brown;font-family:'Palatino Linotype';font-weight:bold">
            @ViewBag.ModalMsg
        </h4>
    </div>
}

@using (Html.BeginForm())
{
    <div class="container">
        <div class="row">
            <div class="col">
                @Html.ActionLink("Усі категорії", "Index", "Home", new { categoryId = "null" }, new { id = "allCateg" })
            </div>
        </div>
        <div class="row clearfix" style="width:100%;margin:auto">
            <div style="border-radius:5px" class="col-md-3">
                <div class="card single_post" style="padding:12px">
                    @foreach (var category in ViewBag.Categories as List<JobSearch.BLL.Dto.CategoryDto>)
                    {
                        var c = category.Id;
                        <p>
                            @Html.ActionLink(category.Name, "Index", "Home", new { categoryId = c }, new { style = "text-decoration:none" })
                        </p>
                    }
                </div>
            </div>

            <div class="col-md-9">
                @foreach (var vacancy in Model)
                {
                    string Path = "~/Images/Vacancies/" + vacancy.Photo;
                    <div class="card single_post" style="padding:12px">
                        <div class="body" style="overflow:auto">
                            <div style="text-align:center">
                                <img style="background-size:cover" src="@Url.Content(Path)" alt="Image doesn't upload..'">
                            </div>
                            <h3>
                                <a style="text-decoration:none;font-weight:bold;color:blue;
                                          font-family:'Palatino Linotype'"
                                   href="/Home/FullVacancy?id=@vacancy.Id">
                                    @vacancy.JobTitle
                                </a>
                            </h3>
                            @{
                                if (vacancy.JobDescription.Count() < 222)
                                {
                                    <h4 style="font-family:'Times New Roman'">
                                        @vacancy.JobDescription
                                    </h4>
                                }
                                else
                                {
                                    <h4 style="font-family:'Times New Roman'">
                                        @vacancy.JobDescription.Substring(0, 222)
                                        @Html.ActionLink("...", "FullVacancy", "Home", new { id = vacancy.Id }, new { style = "font-size:xx-large" })
                                    </h4>
                                }
                            }
                        </div>
                        <div class="row">
                            <div class="col" style="text-align:left;color:darkblue;font-weight:bold">
                                <span>ЗП:</span><span>&nbsp;@vacancy.JobPayment</span>
                            </div>
                            @if (vacancy.EmployerId == ViewBag.UserId && role == "Employer")
                            {
                                <div class="col" style="text-align:center;color:red;font-weight:bold">
                                    @Html.ActionLink("Редагувати", "Vacancy", "Edit",
                                       new { id = vacancy.Id, emplEmail = ViewBag.MyEmail }, new { id = "edit" })
                                </div>
                                <div class="col" style="text-align:center;color:red;font-weight:bold">
                                    @Html.ActionLink("Видалити", "Vacancy", "Delete",
                                       new { id = vacancy.Id }, new { id = "remove" })
                                </div>
                            }
                            <div class="col" style="text-align:right;font-weight:bold;color:darkred">
                                <small style="">Назва компанії:</small>&nbsp;
                                <small>@vacancy.CompanyName</small>
                            </div>
                        </div>
                        <div style="text-align:center">
                            <small style="">Дата публікації:</small>&nbsp;
                            <small>@vacancy.DatePublish</small>
                        </div>
                        @if (role == "RegisterUser")
                        {
                            <div class="row" style="text-align:center">
                                <div class="col">
                                    @Html.ActionLink("Відгукнутись", "Respond", "Message",
                                    new { userEmail = ViewBag.MyEmail, vacancyTitle = vacancy.JobTitle, recipient = vacancy.EmployerId },
                                    new { @class = "btn btn-success" })
                                </div>
                            </div>
                        }
                    </div>
                }
            </div>
        </div>
        @if (role == "Employer")
        {
            <hr />
            <div class="row" style="text-align:center">
                <div class="col">
                    @Html.ActionLink("Додати нову ваканцію", "Vacancy", "Create",
                           new { emplEmail = ViewBag.MyEmail }, new { @class = "btn btn-success" })
                </div>
            </div>
        }
    </div>
}


<style>
    #profile {
        color: blue;
        padding: 9px;
        border-radius: 5px;
        border: 1px solid blue;
        text-decoration: none
    }

        #profile:hover {
            color: darkblue;
            border: 1px solid darkblue;
        }

    #remove {
        text-decoration: none;
        color: red;
        border: 1px solid red;
        border-radius: 5px;
        padding: 5px
    }

        #remove:hover {
            color: darkred;
            border: 1px solid darkred;
        }

    #edit {
        text-decoration: none;
        color: green;
        border: 1px solid green;
        border-radius: 5px;
        padding: 5px
    }

        #edit:hover {
            color: darkgreen;
            border: 1px solid darkgreen;
        }

    #allCateg {
        text-align: center;
        text-decoration: none;
        font-size: x-large;
        color: blue
    }
</style>